config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/login', to: 'login#new'
  post '/login', to: 'login#create'
  delete '/logout', to: 'login#destroy'
  get 'login/main'
  root to: 'login#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
    def main
    end

    def new
    end

    def create
        @user = User.find_by(uid: session_params[:uid], pass: session_params[:pass])

        if @user
            redirect_to login_main_url, notice:'ログインしました！'
        else
            render :login
        end
    end
    
    def destroy
        reset_session
        redirect_to root_url, notice:'ログアウトしました！'
    end

    private
    def session_params
        params.require(:session).permit(:uid, :pass)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L4</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login/main.html.erb
<h1>ログイン成功です！</h1>
<div class="nav-item">
    <%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %>
</div>
      

app/views/login/new.html.erb
<h1>ログイン</h1>

<%= form_with scope: :session, local:  true do |f|%>
  <div class="form-group">
  <%= f.label :uid, 'ユーザーID' %>
  <%= f.text_field :uid, class: 'form-control', id: 'session_uid'%></div>
  <div class="form-group">
  <%= f.label :pass, 'パスワード' %>
  <%= f.password_field :pass, class: 'form-control', id: 'session_pass'%></div>
  <%= f.submit 'ログインする', class: 'btn btn-primary'%>
<% end %>